name: Development Builds
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
      - name: Build with Maven
        run: mvn -B package
      - uses: "actions/upload-artifact@v3"
        with:
          name: "[DevBuild]-MyItems"
          path: ./target/MyItems.jar
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{github.repository}}
          separator: "/"
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: "${{ steps.split.outputs._1 }}"
          embed-title: "Development Builds"
          avatar-url: "https://github.com/${{ steps.split.outputs._0 }}.png"
          embed-color: "65280"
          embed-description: |
            Change Log:
            ${{ github.event.head_commit.message }}
            
            Developer: [`${{ github.actor }}`](https://github.com/${{ github.actor }})
            Download: [`${{ github.run_id }}`](https://nightly.link/${{github.repository}}/actions/runs/${{ github.run_id }}/[DevBuild]-MyItems.zip)
