package api.praya.myitems.builder.socket;

public enum SocketEnum {
   ADDITIONAL_DAMAGE,
   PERCENT_DAMAGE,
   PENETRATION,
   PVP_DAMAGE,
   PVE_DAMAGE,
   ADDITIONAL_DEFENSE,
   PERCENT_DEFENSE,
   HEALTH,
   PVP_DEFENSE,
   PVE_DEFENSE,
   CRITICAL_CHANCE,
   CRITICAL_DAMAGE,
   BLOCK_AMOUNT,
   BLOCK_RATE,
   HIT_RATE,
   DODGE_RATE;
}
